spring:
  profiles:
    default: dev
  application:
    name: order-service

server:
  port: 19092


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0